context:
  version: "16.0.0"

package:
  name: npm-groovy-lint
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/npm-groovy-lint/-/npm-groovy-lint-${{ version }}.tgz
  sha256: 2df028a781eb3cde826c0c4b68f7464d254e1c57f4675548efda44d98cfa3298

build:
  number: 0
  noarch: generic

requirements:
  host:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - npm-groovy-lint --help

about:
  license: GPL-3.0-only
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Lint, format and auto-fix your Groovy / Jenkinsfile / Gradle files using command line
  homepage: https://nvuillam.github.io/npm-groovy-lint
  repository: https://github.com/nvuillam/npm-groovy-lint

extra:
  recipe-maintainers:
    - danielnachun
