context:
  version: "15.2.0"

package:
  name: npm-groovy-lint
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/npm-groovy-lint/-/npm-groovy-lint-${{ version }}.tgz
  sha256: 7167978e88e1574d3fbd666b057bec4ae9314e3ad98797e83affe9eaec3271ba

build:
  number: 0
  noarch: generic

requirements:
  host:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - npm-groovy-lint --help

about:
  license: GPL-3.0-only
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Lint, format and auto-fix your Groovy / Jenkinsfile / Gradle files using command line
  homepage: https://nvuillam.github.io/npm-groovy-lint
  repository: https://github.com/nvuillam/npm-groovy-lint

extra:
  recipe-maintainers:
    - danielnachun
