context:
  version: "15.1.0"

package:
  name: npm-groovy-lint
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/npm-groovy-lint/-/npm-groovy-lint-${{ version }}.tgz
  sha256: c4c69be6cba6a5161970fb91b24b3fd6c48981a49594e2fac7960acedf9080ab

build:
  number: 0
  noarch: generic

requirements:
  host:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - npm-groovy-lint --help

about:
  license: GPL-3.0-only
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Lint, format and auto-fix your Groovy / Jenkinsfile / Gradle files using command line
  homepage: https://nvuillam.github.io/npm-groovy-lint
  repository: https://github.com/nvuillam/npm-groovy-lint

extra:
  recipe-maintainers:
    - danielnachun
