context:
  version: "15.2.1"

package:
  name: npm-groovy-lint
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/npm-groovy-lint/-/npm-groovy-lint-${{ version }}.tgz
  sha256: 8206897d0b2295b8ff91d9f5687e8c85d1ad20bb31d1c568c53afd85e472c298

build:
  number: 0
  noarch: generic

requirements:
  host:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - npm-groovy-lint --help

about:
  license: GPL-3.0-only
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Lint, format and auto-fix your Groovy / Jenkinsfile / Gradle files using command line
  homepage: https://nvuillam.github.io/npm-groovy-lint
  repository: https://github.com/nvuillam/npm-groovy-lint

extra:
  recipe-maintainers:
    - danielnachun
