context:
  version: "17.0.4"

package:
  name: npm-groovy-lint
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/npm-groovy-lint/-/npm-groovy-lint-${{ version }}.tgz
  sha256: a976c9076e7edaddedb7c026bc7f4d87976cbc332a4917e112d0e5e7ed86511c

build:
  number: 0
  noarch: generic

requirements:
  host:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - npm-groovy-lint --help

about:
  license: GPL-3.0-only
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Lint, format and auto-fix your Groovy / Jenkinsfile / Gradle files using command line
  homepage: https://nvuillam.github.io/npm-groovy-lint
  repository: https://github.com/nvuillam/npm-groovy-lint

extra:
  recipe-maintainers:
    - danielnachun
